## Checkout & Checkin Feature Test 구현

#### 1. Checkout 테스트 코드 작성

Unit Test에서 구현한 book checkout, checkin을 Feature Test에서 구현

```bash
php artisan make:test BookCheckoutTest
```



Unit Test의 로직을 기본적으로 따라감

```php
// Unit Test
public function a_book_can_be_checked_out()
{
  $book = factory(Book::class)->create();
  $user = factory(User::class)->create();

  $book->checkout($user);

  $this->assertCount(1, Reservation::all());
  $this->assertEquals($user->id, Reservation::first()->user_id);
  $this->assertEquals($book->id, Reservation::first()->book_id);
  $this->assertEquals(now(), Reservation::first()->checked_out_at);
}
```



Feature Test의 경우 라우트의 엔드포인트를 통해 인증된 유저가 들어올 것이라고 가정을 하고 진행하므로 접근방법이 조금 다름.  book_id를 함께 엔드포인트로 넘김. 만약 제대로 동작할 경우, 나머지 코드는 Unit Test의 코드를 동일하게 사용

-  `actingAs` 헬퍼 메소드는 특정사용자를 현재 사용자로 인증하는 단순한 방법을 제공함.

```php
class BookCheckoutTest extends TestCase
{
    use RefreshDatabase;

    /** @test */
    public function a_book_can_be_checked_out_by_a_signed_in_user()
    {
        $book = factory(Book::class)->create();
        $user = factory(User::class)->create();

        $this->actingAs($user)->post('/checkout/' . $book->id);

        $this->assertCount(1, Reservation::all());
        $this->assertEquals($user->id, Reservation::first()->user_id);
        $this->assertEquals($book->id, Reservation::first()->book_id);
        $this->assertEquals(now(), Reservation::first()->checked_out_at);
    }
}
```



에러가 발생. 상세하게 어떠한 에러인지를 알기 위해 `withoutExceptionHandling` 사용

```bash
Failed asserting that actual size 0 matches expected size 1.
```



라우트 설정

```php
// Exception\NotFoundHttpException : POST http://localhost/checkout/1
Route::post('/checkout/{book}', 'CheckoutBookController@store');
```



`CheckoutBookController` 컨트롤러 생성 후 store 메소드 구현

```php
// BindingResolutionException : Target class [App\Http\Controllers\CheckoutBookController] does not exist.
class CheckoutBookController extends Controller
{
    public function store()
    {
    }
}
```



Unit Test를 통해서 바로 다음 어떠한 로직/코드를 짜야하는지 쉽게 알 수 있음. Route Model Binding을 통해 Book 객체를 저장시키며, `auth()->user()` 를 통해 인증된 유저를 인자로 받아 `Book@checkout` 를 실행시킴.

```php
class CheckoutBookController extends Controller
{
    public function store(Book $book)
    {
        $book->checkout(auth()->user());
    }
}
```



나머지 코드는 Unit Test 때와 그대로 동일하게 작성

```php
public function a_book_can_be_checked_out_by_a_signed_in_user()
{
  $book = factory(Book::class)->create();
  $user = factory(User::class)->create();

  $this->actingAs($user)->post('/checkout/' . $book->id);

  $this->assertCount(1, Reservation::all());
  $this->assertEquals($user->id, Reservation::first()->user_id);
  $this->assertEquals($book->id, Reservation::first()->book_id);
  $this->assertEquals(now(), Reservation::first()->checked_out_at);
}
```



#### 2-1. Checkout 테스트 케이스 확장 - 인증된 유저만 체크아웃 가능

인증되지 않은 유저가 체크아웃을 진행할 경우, 로그인 페이지로 리다이렉트하는 테스트 케이스 작성.  Reservation은 이루어지지 않았으므로 객체의 수는 0개여야 함.

```php
/** @test */
public function only_signed_in_users_can_checkout_a_book()
{
  $book = factory(Book::class)->create();

  $this->post('/checkout/' . $book->id)
    ->assertRedirect('/login');

  $this->assertCount(0, Reservation::all());
}
```



테스트를 돌려보면 500 에러가 발생함. `withoutExceptionHandling` 를 통해 출력을 해보면 user_id가 존재하지 않음을 알수 있음. (`Book@checkout`에서 reservation 객체를 생성할 때 user_id가 필요하나, 누락되어있음)

```php
// Response status code [500] is not a redirect status code.

// Book.php
public function checkout($user)
{
  $this->reservations()->create([
    'user_id' => $user->id,
    'checked_out_at' => now(),
  ]);
}
```



생성자 메소드를 통해 라라벨의 미들웨어중 하나인 `Authenticate` 를 동작시킴  `Authenticate`  파일을 살펴보면 인증에 실패했을 경우, 로그인 페이지로 리다이렉트 시키는 로직이 구현되어있음.

```php
// Http\Middleware\Authenticate.php
class Authenticate extends Middleware
{
    protected function redirectTo($request)
    {
        if (! $request->expectsJson()) {
            return route('login');
        }
    }
}
```

```php
class CheckoutBookController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function store(Book $book)
    {
        $book->checkout(auth()->user());
    }
}
```



테스트를 동작시키면 500에러가 발생함. 현재 Laravel authentication을 이용하고 있지만,  그에 따른 라우트 설정을 해주지 않았음(로그인, 로그아웃 등의 라우트가 존재하지 않음). 

```php
php artisan make:auth //  if  laravel version below 6.0
composer require laravel/ui --dev // else
```



이후 테스트를 돌려보면 성공적으로 작동하는 것을 알 수 있음.



#### 2-2. Checkout 테스트 케이스 확장 - 책이 존재할 때만 체크아웃 가능

존재하지 않는 book_id를 하드코딩하여 입력한 후, `assertStatus` 가 404(not found)가 뜨도록 코드 작성

```php
/** @test */
public function only_real_books_can_be_checked_out()
{
  $this->actingAs(factory(User::class)->create())
    ->post('/checkout/123')
    ->assertStatus(404);

  $this->assertCount(0, Reservation::all());
}
```



#### 3. Checkin 테스트 코드 작성

기본적인 코드는 `a_book_can_be_checked_out_by_a_signed_in_user` 메소드를 토대로 만드나, reservation 객체를 생성하려면  `Book@checkout`이 선행되어야함. 

```php
/** @test */
public function a_book_can_be_checked_in_by_a_signed_in_user()
{
  $book = factory(Book::class)->create();
  $user = factory(User::class)->create();
  
  // Reservation 객체를 생성하기 위히 우선 체크아웃 로직 동작시킴
  $this->actingAs($user)->post('/checkout/' . $book->id); 

  $this->actingAs($user)->post('/checkin/' . $book->id);

  $this->assertCount(1, Reservation::all());
  $this->assertEquals($user->id, Reservation::first()->user_id);
  $this->assertEquals($book->id, Reservation::first()->book_id);
  $this->assertEquals(now(), Reservation::first()->checked_in_at);
}
```



아래 코드에서 에러가 발생함.

``` php
// null does not match expected type "object".
$this->assertEquals(now(), Reservation::first()->checked_in_at);
```



`withoutExceptionHandling`으로 살펴보면 라우트 설정이 되지 않은 것이 확인 가능. 라우트를 생성한 후, `CheckinBookController` 컨트롤러를 생성  & store 메소드를 구현함.

```bash
NotFoundHttpException : POST http://localhost/checkin/1
```

```bash
Route::post('/checkin/{book}', 'CheckinBookController@store');

class CheckinBookController extends Controller
{
    public function store()
    {
    }
}
```



정확한 상세 정보를 확인할 수 없는 에러가 발생하나, Unit test를 통해 어떤 로직을 구현해야하는지를 알 수 있음.

- `$book->checkin($user);` 

```bash
null does not match expected type "object".
```

```php
use App\Book;

class CheckinBookController extends Controller
{
    public function store(Book $book)
    {
        $book->checkin(auth()->user());
    }
}
```



나머지 코드는 Unit Test 때와 그대로 동일하게 작성

```php
public function a_book_can_be_checked_in_by_a_signed_in_user()
{
  $this->withoutExceptionHandling();

  $book = factory(Book::class)->create();
  $user = factory(User::class)->create();
  $this->actingAs($user)->post('/checkout/' . $book->id);

  $this->actingAs($user)->post('/checkin/' . $book->id);

  $this->assertCount(1, Reservation::all());
  $this->assertEquals($user->id, Reservation::first()->user_id);
  $this->assertEquals($book->id, Reservation::first()->book_id);
  $this->assertEquals(now(), Reservation::first()->checked_in_at);
}
```



#### 4-1. Checkin 테스트 케이스 확장 - 인증된 유저만 체크아웃 가능

"인증된 유저만 체크아웃 가능" - `only_signed_in_users_can_checkout_a_book()` 를 기반으로 코드 작성

```php
public function only_signed_in_users_can_checkin_a_book()
{
  $this->withoutExceptionHandling();

  $book = factory(Book::class)->create();

  $this->post('/checkout/' . $book->id)->assertRedirect('/login');
  $this->post('/checkin/' . $book->id)->assertRedirect('/login');

  $this->assertCount(0, Reservation::all());
}
```



테스트를 실행시켜보면 500에러(unauthorized) 발생. 기존의 코드는 로그인이 되어있지 않은 경우에 로그인 엔드포인트로 리다이렉트시키는 코드인데, 지금의 테스트 코드는 체크인을 테스트하는 것임. 그러므로 우선, 로그인은 정상적으로 동작해야함. `actingAs` 메소드와 `factory`  메소드를 활용하여 로그인이 동작하도록 코드 수정

```php
$this->post('/checkout/' . $book->id)->assertRedirect('/login');
```

```php
public function only_signed_in_users_can_checkin_a_book()
{
  $book = factory(Book::class)->create();
  $this->actingAs(factory(User::class)->create())
    ->post('/checkout/' . $book->id);

  $this->post('/checkin/' . $book->id)
    ->assertRedirect('/login');

  $this->assertCount(0, Reservation::all());
}
```



CheckinBookController의 생성자 메소드로 auth 미들웨어를 추가시킴

```php
class CheckinBookController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
```



에러가 발생.  로그인 코드를 통해 로그인 상태가 유지되고 있어서 200 코드를 반환시키고 있음. 따라서, 로그 아웃 코드를 추가로 삽입해야함.

```php
//Response status code [200] is not a redirect status code.
//Failed asserting that false is true.

// 문제가 되는 부분
$this->post('/checkin/' . $book->id)->assertRedirect('/login');
```

```php
use Illuminate\Support\Facades\Auth;

/** @test */
public function only_signed_in_users_can_checkin_a_book()
{
  $book = factory(Book::class)->create();

  $this->actingAs(factory(User::class)->create())
    ->post('/checkout/' . $book->id);

  Auth::logout();

  $this->post('/checkin/' . $book->id)
    ->assertRedirect('/login');

  $this->assertCount(0, Reservation::all());
}
```



Reservation 객체가 생성되었으므로 assertCount의 첫번째 인수에는 1을 넣어주며, 체크인이 실제로 되지 않았으므로 그 값이 null이라는 것을 확인시켜주는 코드를 추가로 작성함

```php
$this->assertCount(1, Reservation::all());
$this->assertNull(Reservation::first()->checked_in_at);
```



최종적으로 완성된 코드는 아래와 같음.

```php
public function only_signed_in_users_can_checkin_a_book()
{
  $book = factory(Book::class)->create();

  $this->actingAs(factory(User::class)->create())
    ->post('/checkout/' . $book->id);

  Auth::logout();

  $this->post('/checkin/' . $book->id)
    ->assertRedirect('/login');

  $this->assertCount(1, Reservation::all());
  $this->assertNull(Reservation::first()->checked_in_at);
}
```



#### 4-2. Checkin 테스트 케이스 확장 - 체크아웃 되지 않은 책을 체크인

체크아웃되지 않은 책을 체크인할 경우 404에러를 반환하는 것이 일반적임. 

-  checkin 테스트 코드를 기반으로 작성하되, `Book@checkout` 을 동작시키는 코드는 삭제시킴.

- Reservation 객체는 생성되지 않으므로 0으로 만들며 나머지 코드는 삭제시킴
- 그리고 /checkin/ 엔드포인트에 대하여 404를 반환하는 assert 코드 구현

```php
 public function a_404_is_thrown_if_a_book_is_not_checked_out_first()
{
  $book = factory(Book::class)->create();
  $user = factory(User::class)->create();

  $this->actingAs($user)
    ->post('/checkin/' . $book->id)
    ->assertStatus(404);

  $this->assertCount(0, Reservation::all());
}
```



500 에러를 발생시킴. `withoutExceptionHandling` 를 통해 에러 디테일 확인. 에러가 발생하는 `CheckinBookController@store` 수정

```php
public function store(Book $book)
{
  try {
    $book->checkin(auth()->user());
  } catch (\Exception $e) {
    return response([], 404);
  }
}
```
